name: fmark_camera
description: Fmark Camera app with layered customizable watermarks.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  video_player: ^2.7.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.2.0
  intl: ^0.20.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  uuid: ^4.4.0
  collection: ^1.18.0
  path: ^1.8.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
